source:
  # ポスターに使いたい画像ファイルを入れるディレクトリです。
  # jjpg|jpeg|png|gif|tif
  # 名前順に読み込まれます。
  path: './source/'
  dummy: './dummy.jpg' # ダミーデータです。4*4でやりたいのに画像が5枚ぐらいしか無いときとかは残りはこれで埋められます。

target:
  path: './target/result.png' # 出力先
  parts_of:
    # 画像一枚あたりの解像度です。最終的には(width*row)*(height*col)の解像度で出力されます。
    width: 256
    height: 512
    border: 64 # 画像同士のマージン: px
    color: 'transparent' # マージンの色 transparentで透明, 詳細: https://rmagick.github.io/imusage.html#color_names
  combine:
    # 結合したい行数と列数です。
    row: 4
    col: 4
