posters:
  # Dir.globで扱える形式のパターンマッチで拡張子を見てます。
  pattern: '*.{png,jpg,jpeg,gif,tif,bmp}'
  source: './source/'       # 合成元フォルダ
  target: './target/'       # 生成先フォルダ
  extension: 'png'          # 出力拡張子
  format: 'png32'           # ビット深度
  dummy: './dummy.png'      # ダミーポスター
  wanted: './wanted.png'    # 募集ポスター
  size:                     # ポスターごとの
    width: 700              # 横px
    height: 990             # 縦px

montage:                    # パネル
  background_color: 'transparent' # 背景色
  geometry:
    distance: 2             # ポスター同士の距離(distance * 2が実際の値だけど)
  tile: '4x4'               # ポスターの枚数 (横x縦)